-- Catalog rows for the live Proxmox test server.
--
-- **Generated by `tools/proxmox/generate-lab-seed.mjs`. Do not hand-edit.**
-- Refresh with `pnpm run survey:proxmox` then `pnpm run proxmox:generate-seed`.
--
-- Additive, and deliberately so. `0001_phase3_fake.sql` is not edited: the integration suites,
-- the Postman collection and the committed Phase 4 and Phase 6 evidence all depend on its values,
-- and its `ON CONFLICT DO NOTHING` means an edit would not take effect on an existing database
-- anyway. Every row here carries a new identifier, so the fake path is untouched and cannot
-- accidentally select one of these.
--
-- `loadAcceptanceContext` resolves the provider profile *through the image* and refuses unless
-- `profile.network_id = network.id`, so the image, profile and network below have to be mutually
-- consistent. They are also cross-checked against the `PROXMOX_*` environment at runtime by
-- `assertNetwork` and `assertDirectProfile`; `pnpm run proxmox:check-config` asserts that
-- agreement up front rather than leaving it to surface as an opaque protocol error at create time.
--
-- Derived from the survey of 2026-09-17: `docs/verification/evidence/testsrv-survey.json`.
--
-- WHY `ON CONFLICT DO UPDATE` here where seed 0001 uses DO NOTHING: these rows describe a real
-- server that changes. The exclusion list in particular is a measurement with a date on it, and a
-- re-seed that silently kept a stale one would hand out an address that is already live.

BEGIN;

-- A project of its own, with a deliberately tight quota.
--
-- SAFE-030 requires live-provider work to have a small explicit operation cap. The reserved VMID
-- interval holds 100 identifiers; this quota permits 3 instances, so a runaway loop
-- exhausts the quota long before it exhausts the interval.
INSERT INTO control.projects (id, name, enabled, created_at, updated_at)
VALUES ('00000000-0000-4000-8000-0000000000a1', 'testsrv-lab', true, now(), now())
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO control.quotas (
  project_id, instances, cpu_count, memory_mib, disk_gib, ipv4_addresses, snapshots, updated_at
)
VALUES (
  '00000000-0000-4000-8000-0000000000a1', 3, 8, 16384, 192,
  3, 8, now()
)
ON CONFLICT (project_id) DO UPDATE SET
  instances = EXCLUDED.instances,
  cpu_count = EXCLUDED.cpu_count,
  memory_mib = EXCLUDED.memory_mib,
  disk_gib = EXCLUDED.disk_gib,
  ipv4_addresses = EXCLUDED.ipv4_addresses,
  snapshots = EXCLUDED.snapshots,
  updated_at = now();

-- The bridge as it actually is: 192.168.4.1/22, so the network address is 192.168.4.0/22.
--
-- The exclusions are the 110 addresses measured as already live on this bridge. The
-- allocator returns the lowest free address, so instances land at 192.168.4.2 upward and are
-- nowhere near the occupied region — but it knows only its own leases plus whatever it is told
-- here, so without this list it would eventually walk into them. It cannot see an address a guest
-- configured internally rather than through cloud-init; `assertIpv4Available` rechecks live VM
-- configuration immediately before the network mutation (SAFE-025), which covers the declared
-- cases and cannot cover the undeclared ones.
INSERT INTO control.networks (
  id, name, ipv4_cidr, gateway, dns_servers, exclusions, enabled, created_at, updated_at
)
VALUES (
  'testsrv-vmbr1',
  'Test server vmbr1',
  '192.168.4.0/22',
  '192.168.4.1',
  '["1.1.1.1"]',
  '[
    "192.168.7.102", "192.168.7.103", "192.168.7.106", "192.168.7.107", "192.168.7.108",
    "192.168.7.111", "192.168.7.112", "192.168.7.115", "192.168.7.116", "192.168.7.117",
    "192.168.7.118", "192.168.7.119", "192.168.7.120", "192.168.7.121", "192.168.7.125",
    "192.168.7.126", "192.168.7.127", "192.168.7.128", "192.168.7.129", "192.168.7.130",
    "192.168.7.131", "192.168.7.132", "192.168.7.133", "192.168.7.134", "192.168.7.135",
    "192.168.7.136", "192.168.7.137", "192.168.7.138", "192.168.7.139", "192.168.7.140",
    "192.168.7.141", "192.168.7.143", "192.168.7.146", "192.168.7.148", "192.168.7.149",
    "192.168.7.150", "192.168.7.151", "192.168.7.152", "192.168.7.154", "192.168.7.155",
    "192.168.7.156", "192.168.7.157", "192.168.7.158", "192.168.7.159", "192.168.7.160",
    "192.168.7.161", "192.168.7.164", "192.168.7.166", "192.168.7.167", "192.168.7.168",
    "192.168.7.169", "192.168.7.170", "192.168.7.172", "192.168.7.173", "192.168.7.174",
    "192.168.7.180", "192.168.7.181", "192.168.7.182", "192.168.7.183", "192.168.7.184",
    "192.168.7.185", "192.168.7.188", "192.168.7.189", "192.168.7.191", "192.168.7.192",
    "192.168.7.194", "192.168.7.195", "192.168.7.196", "192.168.7.197", "192.168.7.198",
    "192.168.7.199", "192.168.7.200", "192.168.7.201", "192.168.7.202", "192.168.7.203",
    "192.168.7.204", "192.168.7.205", "192.168.7.206", "192.168.7.207", "192.168.7.211",
    "192.168.7.213", "192.168.7.214", "192.168.7.215", "192.168.7.216", "192.168.7.217",
    "192.168.7.220", "192.168.7.221", "192.168.7.222", "192.168.7.223", "192.168.7.226",
    "192.168.7.227", "192.168.7.229", "192.168.7.230", "192.168.7.233", "192.168.7.234",
    "192.168.7.236", "192.168.7.238", "192.168.7.239", "192.168.7.240", "192.168.7.241",
    "192.168.7.242", "192.168.7.244", "192.168.7.245", "192.168.7.246", "192.168.7.247",
    "192.168.7.248", "192.168.7.249", "192.168.7.250", "192.168.7.251", "192.168.7.252"
  ]',
  true,
  now(),
  now()
)
ON CONFLICT (id) DO UPDATE SET
  ipv4_cidr = EXCLUDED.ipv4_cidr,
  gateway = EXCLUDED.gateway,
  dns_servers = EXCLUDED.dns_servers,
  exclusions = EXCLUDED.exclusions,
  enabled = EXCLUDED.enabled,
  updated_at = now();

-- `credential_reference` is a NAME, never a value. SAFE-036 governs what enters history; the
-- token itself lives only in the gitignored credentials file.
INSERT INTO control.provider_profiles (
  id, provider_type, state, endpoint, cluster_alias, compute_target, image_source_reference,
  storage_target, network_attachment, resource_id_minimum, resource_id_maximum, network_id,
  credential_reference, created_at, updated_at
)
VALUES (
  'proxmox-testsrv',
  'proxmox',
  'active',
  'https://testsrv.mosalam.com:8006',
  'testsrv',
  'proxtest',
  '9100',
  'local',
  'vmbr1',
  910000,
  910099,
  'testsrv-vmbr1',
  'PROXMOX_API_TOKEN_ID/PROXMOX_API_TOKEN_SECRET',
  now(),
  now()
)
ON CONFLICT (id) DO UPDATE SET
  provider_type = EXCLUDED.provider_type,
  state = EXCLUDED.state,
  endpoint = EXCLUDED.endpoint,
  cluster_alias = EXCLUDED.cluster_alias,
  compute_target = EXCLUDED.compute_target,
  image_source_reference = EXCLUDED.image_source_reference,
  storage_target = EXCLUDED.storage_target,
  network_attachment = EXCLUDED.network_attachment,
  resource_id_minimum = EXCLUDED.resource_id_minimum,
  resource_id_maximum = EXCLUDED.resource_id_maximum,
  network_id = EXCLUDED.network_id,
  credential_reference = EXCLUDED.credential_reference,
  updated_at = now();

INSERT INTO control.images (
  id, name, provider_profile_id, enabled, architecture, created_at, updated_at
)
VALUES (
  'ubuntu-noble-2404', 'Ubuntu Noble 24.04', 'proxmox-testsrv', true, 'x86_64', now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  provider_profile_id = EXCLUDED.provider_profile_id,
  enabled = EXCLUDED.enabled,
  updated_at = now();

-- No new flavours.
--
-- Template 9100 is 2 vCPU, 4096 MiB and 32 GiB, which `lab-small` already
-- describes exactly. That matters rather than being a coincidence: `assertResources` refuses a
-- create unless the requested disk equals the template's disk exactly, so a flavour that
-- disagreed by a single gibibyte would fail every create. `lab-medium` (4 / 8192 / 64) is the
-- resize target, and growing 32 GiB to 64 GiB is a valid grow.

COMMIT;
