packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@bufbuild/buf': true
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  less: true
  nx: true
  unrs-resolver: true
  '@nestjs/core': false
