import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { parse as parseYaml } from 'yaml';

const GENERATED_NOTICE =
  '<!-- Generated by tools/contracts/generate-docs.mjs. Do not edit by hand. -->';
const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete']);
const outputDirectory = 'docs/contracts';

await mkdir(outputDirectory, { recursive: true });

const openApi = JSON.parse(
  await readFile('packages/contracts/src/generated/openapi.v1.json', 'utf8'),
);
const asyncApi = parseYaml(
  await readFile('packages/contracts/asyncapi/control-plane.v1.yaml', 'utf8'),
);
const eventSchema = JSON.parse(
  await readFile('packages/contracts/asyncapi/schemas/control-plane-events.v1.schema.json', 'utf8'),
);
const rpcPolicies = JSON.parse(
  await readFile('packages/contracts/proto/rpc-policies.v1.json', 'utf8'),
);
const protoFiles = [
  'packages/contracts/proto/privatecloud/common/v1/common.proto',
  'packages/contracts/proto/privatecloud/controlplane/v1/control_plane.proto',
  'packages/contracts/proto/privatecloud/provider/v1/provider.proto',
];

function escapeCell(value) {
  if (value === undefined || value === null || value === '') return '-';
  return String(value).replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function table(headers, rows) {
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`),
  ].join('\n');
}

function referenceName(reference) {
  return reference?.split('/').at(-1) ?? '-';
}

function resolveInternalReference(document, value) {
  if (!value?.$ref?.startsWith('#/')) return value;
  return value.$ref
    .slice(2)
    .split('/')
    .reduce(
      (current, segment) => current?.[segment.replaceAll('~1', '/').replaceAll('~0', '~')],
      document,
    );
}

function schemaType(schema = {}) {
  if (schema.$ref) return referenceName(schema.$ref);
  if (schema.const !== undefined) return `const ${JSON.stringify(schema.const)}`;
  if (schema.enum) return schema.enum.map(String).join(' \| ');
  if (schema.oneOf) return schema.oneOf.map(schemaType).join(' or ');
  if (schema.allOf) return schema.allOf.map(schemaType).join(' + ');
  if (schema.type === 'array') return `array<${schemaType(schema.items)}>`;
  return Array.isArray(schema.type) ? schema.type.join(' or ') : (schema.type ?? 'object');
}

function constraints(schema = {}) {
  const keys = [
    'format',
    'pattern',
    'minimum',
    'maximum',
    'minLength',
    'maxLength',
    'minItems',
    'maxItems',
    'multipleOf',
    'default',
    'readOnly',
  ];
  const values = keys
    .filter((key) => schema[key] !== undefined)
    .map((key) => `${key}=${JSON.stringify(schema[key])}`);
  if (schema.enum) values.push(`enum=${schema.enum.join(',')}`);
  if (schema.const !== undefined) values.push(`const=${JSON.stringify(schema.const)}`);
  return values.join('; ') || '-';
}

function operationSchema(operation, kind) {
  if (kind === 'request') {
    const media = operation.requestBody?.content ?? {};
    const schema = Object.values(media)[0]?.schema;
    return schemaType(schema);
  }
  const success = Object.entries(operation.responses ?? {}).find(([status]) =>
    /^2\d\d$/.test(status),
  );
  const response = resolveInternalReference(openApi, success?.[1]);
  const media = response?.content ?? {};
  return schemaType(Object.values(media)[0]?.schema);
}

function responseCodes(operation) {
  return Object.keys(operation.responses ?? {}).join(', ');
}

const restRows = [];
for (const [path, pathItem] of Object.entries(openApi.paths)) {
  for (const [method, operation] of Object.entries(pathItem)) {
    if (!HTTP_METHODS.has(method)) continue;
    restRows.push([
      method.toUpperCase(),
      `\`${path}\``,
      operation.operationId,
      operation['x-audience'],
      operation.security?.length === 0 ? 'Public probe' : 'Bearer token',
      operation['x-idempotency'],
      operationSchema(operation, 'request'),
      operationSchema(operation, 'response'),
      responseCodes(operation),
      (operation['x-error-codes'] ?? []).join(', '),
      operation['x-max-body-bytes'],
      (operation['x-requirements'] ?? []).join(', '),
    ]);
  }
}

await writeFile(
  `${outputDirectory}/rest-api.md`,
  `${GENERATED_NOTICE}\n# REST API contract\n\nSource: \`packages/contracts/openapi/control-plane.v1.yaml\`. A \`202\` response means the intent and operation were durably accepted, not that provider work completed.\n\n${table(
    [
      'Method',
      'Path',
      'Operation',
      'Audience',
      'Auth',
      'Idempotency',
      'Request',
      'Success body',
      'HTTP statuses',
      'Stable errors',
      'Max body bytes',
      'Requirements',
    ],
    restRows,
  )}\n`,
  'utf8',
);

function parseProto(source) {
  const packageName = source.match(/^package\s+([\w.]+);/m)?.[1] ?? 'unknown';
  const services = [];
  const fields = [];
  let currentService;
  let currentMessage;
  let blockDepth = 0;

  for (const line of source.split('\n')) {
    const serviceMatch = line.match(/^service\s+(\w+)\s*\{/);
    const messageMatch = line.match(/^message\s+(\w+)\s*\{/);
    if (serviceMatch) {
      currentService = serviceMatch[1];
      blockDepth = 1;
      continue;
    }
    if (messageMatch) {
      currentMessage = messageMatch[1];
      blockDepth = 1;
      continue;
    }

    if (currentService) {
      const rpcMatch = line.match(/^\s*rpc\s+(\w+)\(([^)]+)\)\s+returns\s+\(([^)]+)\)/);
      if (rpcMatch) {
        services.push({
          service: `${packageName}.${currentService}`,
          method: rpcMatch[1],
          request: rpcMatch[2],
          response: rpcMatch[3],
        });
      }
    }

    if (currentMessage) {
      const fieldMatch = line.match(/^\s*(optional\s+|repeated\s+)?([.\w]+)\s+(\w+)\s*=\s*(\d+)/);
      if (fieldMatch) {
        fields.push({
          message: `${packageName}.${currentMessage}`,
          field: fieldMatch[3],
          type: `${fieldMatch[1]?.trim() ?? 'required'} ${fieldMatch[2]}`,
          tag: fieldMatch[4],
        });
      }
    }

    blockDepth += (line.match(/\{/g) ?? []).length;
    blockDepth -= (line.match(/\}/g) ?? []).length;
    if (blockDepth <= 0) {
      currentService = undefined;
      currentMessage = undefined;
      blockDepth = 0;
    }
  }
  return { services, fields };
}

const protoDocuments = await Promise.all(
  protoFiles.map(async (file) => ({ file, parsed: parseProto(await readFile(file, 'utf8')) })),
);
const grpcMethods = protoDocuments.flatMap(({ parsed }) => parsed.services);
const policyByMethod = new Map();
for (const rule of rpcPolicies.rules) {
  for (const method of rule.methods) policyByMethod.set(`${rule.service}/${method}`, rule);
}
const grpcRows = grpcMethods.map((rpc) => {
  const policy = policyByMethod.get(`${rpc.service}/${rpc.method}`);
  return [
    rpc.service,
    rpc.method,
    rpc.request,
    rpc.response,
    policy?.audience,
    policy?.authentication,
    policy?.deadlineMs,
    policy?.idempotency,
    rpcPolicies.errorSets[policy?.kind]?.join(', '),
    policy?.requirements.join(', '),
  ];
});
await writeFile(
  `${outputDirectory}/grpc-api.md`,
  `${GENERATED_NOTICE}\n# gRPC API contract\n\nSources: \`packages/contracts/proto\` and \`rpc-policies.v1.json\`. Deadlines are caller budgets; a provider mutation deadline does not prove that the provider rejected the mutation.\n\n${table(
    [
      'Service',
      'RPC',
      'Request',
      'Response',
      'Audience',
      'Authentication',
      'Deadline ms',
      'Idempotency',
      'Errors',
      'Requirements',
    ],
    grpcRows,
  )}\n`,
  'utf8',
);

const eventUsage = new Map();
function operationMessageName(reference) {
  const segments = reference?.split('/') ?? [];
  if (segments[1] !== 'channels' || segments[3] !== 'messages') return referenceName(reference);
  const channelMessage = asyncApi.channels?.[segments[2]]?.messages?.[segments[4]];
  return referenceName(channelMessage?.$ref);
}
for (const [operationName, operation] of Object.entries(asyncApi.operations)) {
  for (const message of operation.messages ?? []) {
    const name = operationMessageName(message.$ref);
    const usage = eventUsage.get(name) ?? {
      producers: new Set(),
      consumers: new Set(),
      operations: [],
    };
    const services = String(operation['x-service']).split(',');
    for (const service of services) {
      usage[operation.action === 'send' ? 'producers' : 'consumers'].add(service);
    }
    usage.operations.push(operationName);
    eventUsage.set(name, usage);
  }
}
const channelByMessage = new Map();
for (const channel of Object.values(asyncApi.channels)) {
  for (const message of Object.values(channel.messages)) {
    channelByMessage.set(referenceName(message.$ref), channel);
  }
}
const eventRows = Object.entries(asyncApi.components.messages).map(([name, message]) => {
  const usage = eventUsage.get(name);
  const channel = channelByMessage.get(name);
  return [
    channel?.address,
    name,
    usage ? [...usage.producers].join(', ') : '-',
    usage ? [...usage.consumers].join(', ') : '-',
    channel?.['x-partition-key'],
    channel?.['x-delivery'],
    referenceName(message.payload.$ref),
    (message['x-requirements'] ?? []).join(', '),
  ];
});
await writeFile(
  `${outputDirectory}/events.md`,
  `${GENERATED_NOTICE}\n# Kafka event contract\n\nSources: \`packages/contracts/asyncapi/control-plane.v1.yaml\` and \`schemas/control-plane-events.v1.schema.json\`. The delivery guarantee is at-least-once; consumers deduplicate by \`eventId\` plus replay generation and preserve per-aggregate ordering with \`partitionKey\`. Maximum encoded payload: ${asyncApi['x-max-payload-bytes'].toLocaleString()} bytes.\n\n${table(
    [
      'Topic',
      'Message',
      'Producer',
      'Consumer',
      'Partition field',
      'Delivery',
      'Payload schema',
      'Requirements',
    ],
    eventRows,
  )}\n\n## Transport headers\n\n${table(
    ['Header', 'Type', 'Required', 'Constraints', 'Description', 'Classification', 'Telemetry'],
    Object.entries(asyncApi['x-transport-headers']).map(([name, header]) => [
      name,
      schemaType(header),
      header.required ? 'yes' : 'no',
      constraints(header),
      header.description,
      header['x-classification'],
      header['x-telemetry'],
    ]),
  )}\n`,
  'utf8',
);

const fieldRows = [];
function addJsonFields(origin, schemaName, schema, inheritedRequired = new Set()) {
  const required = new Set([...(schema.required ?? []), ...inheritedRequired]);
  for (const [field, property] of Object.entries(schema.properties ?? {})) {
    fieldRows.push([
      origin,
      schemaName,
      field,
      schemaType(property),
      required.has(field) ? 'yes' : 'no',
      constraints(property),
      property.description,
      property['x-classification'] ?? 'operational',
      property['x-telemetry'] ?? 'allowed-if-low-cardinality',
    ]);
    if (property.properties) addJsonFields(origin, `${schemaName}.${field}`, property);
  }
  for (const branch of schema.allOf ?? []) {
    if (!branch.$ref) addJsonFields(origin, schemaName, branch, required);
  }
}
for (const [name, schema] of Object.entries(openApi.components.schemas)) {
  addJsonFields('OpenAPI', name, schema);
}
for (const [name, schema] of Object.entries(eventSchema.$defs)) {
  addJsonFields('JSON Schema', name, schema);
}
for (const [name, header] of Object.entries(asyncApi['x-transport-headers'])) {
  fieldRows.push([
    'AsyncAPI header',
    'KafkaTransportHeaders',
    name,
    schemaType(header),
    header.required ? 'yes' : 'no',
    constraints(header),
    header.description,
    header['x-classification'],
    header['x-telemetry'],
  ]);
}
for (const { parsed } of protoDocuments) {
  for (const field of parsed.fields) {
    fieldRows.push([
      'Protobuf',
      field.message,
      field.field,
      field.type,
      field.type.startsWith('optional') || field.type.startsWith('repeated')
        ? 'no'
        : 'proto3 semantic',
      `field=${field.tag}`,
      '-',
      'operational',
      'allowed-if-low-cardinality',
    ]);
  }
}
await writeFile(
  `${outputDirectory}/fields.md`,
  `${GENERATED_NOTICE}\n# Contract field catalog\n\nEvery field declared by the OpenAPI components, event JSON Schema definitions, and protobuf messages is listed below. Security-sensitive exceptions are explicit; unspecified operational fields are still subject to the logging and metrics cardinality rules.\n\n${table(
    [
      'Source',
      'Schema/message',
      'Field',
      'Type',
      'Required',
      'Constraints/tag',
      'Description',
      'Classification',
      'Telemetry',
    ],
    fieldRows,
  )}\n`,
  'utf8',
);

const problem = openApi.components.schemas.ProblemDetails;
const errorCodes = problem.properties.code.enum;
const usedBy = new Map(errorCodes.map((code) => [code, []]));
for (const row of restRows) {
  for (const code of String(row[9]).split(', ').filter(Boolean)) usedBy.get(code)?.push(row[2]);
}
const errorRows = errorCodes.map((code) => [
  code,
  usedBy.get(code).join(', ') || 'Reserved contract code',
]);
await writeFile(
  `${outputDirectory}/errors.md`,
  `${GENERATED_NOTICE}\n# Error contract\n\nREST failures use RFC 9457 \`application/problem+json\`. The stable \`code\` is safe for automation; \`detail\` is tenant-safe text and is not a substitute for operator evidence. gRPC canonical statuses are documented in the [gRPC table](grpc-api.md).\n\n${table(['Stable REST code', 'Operations'], errorRows)}\n`,
  'utf8',
);

const generatedDocuments = [
  `${outputDirectory}/rest-api.md`,
  `${outputDirectory}/grpc-api.md`,
  `${outputDirectory}/events.md`,
  `${outputDirectory}/errors.md`,
  `${outputDirectory}/fields.md`,
];
const formatResult = spawnSync('node_modules/.bin/prettier', ['--write', ...generatedDocuments], {
  encoding: 'utf8',
  stdio: 'inherit',
});
if (formatResult.error) throw formatResult.error;
if (formatResult.status !== 0) {
  throw new Error(`Prettier exited with status ${formatResult.status ?? 'unknown'}`);
}

console.log(
  `Generated contract documentation: ${restRows.length} REST operations, ${grpcRows.length} RPCs, ${eventRows.length} messages, and ${fieldRows.length} field rows.`,
);
