export const CONTROL_PLANE_APPLICATION = Symbol('CONTROL_PLANE_APPLICATION');
export const POSTGRES_DATABASE = Symbol('POSTGRES_DATABASE');
export const PROJECTION_STORE = Symbol('PROJECTION_STORE');
